"""Add lab log entries table

Revision ID: 9036ac1a9c74
Revises: 
Create Date: 2025-10-01 19:23:29.792623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9036ac1a9c74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('solution_name', sa.String(), nullable=False),
    sa.Column('volume_ml', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_log_entries_id'), 'lab_log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_lab_log_entries_solution_name'), 'lab_log_entries', ['solution_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_log_entries_solution_name'), table_name='lab_log_entries')
    op.drop_index(op.f('ix_lab_log_entries_id'), table_name='lab_log_entries')
    op.drop_table('lab_log_entries')
    # ### end Alembic commands ###
